### ISSUE TITLE
Setup config and add context

### ISSUE THREAD

**Issue by anymaniax** [honeybadger-io/honeybadger-react#105]
Hey,

Like in your vue.js package it's good be more simple to only pass the config to the component.

What do you think?

**Comment by anymaniax** [comment]
Could be also interesting to automatically setup a context with a hooks to access easily the instance from anywhere in the application

**Comment by joshuap** [comment]
@JasonTrue may correct me if I'm wrong, but I *think* that you can still get the singleton instance of Honeybadger anywhere you do `import Honeybadger from 'honeybadger-js'`. If that's the case, I think I prefer that to React manage the instance (because it seems preferable to inject the dependency).
