### ISSUE TITLE
Double notification

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-react#247]
I've noticed that a few React apps—including the [example app](https://github.com/honeybadger-io/honeybadger-react/tree/master/example)—report the same error twice. Why is that?

**Comment by miktirr** [comment]
Maybe this is just caused by React rendering twice in the development mode? I investigated duplicate reports in our project, and those seemed to happen only when the app was run in the development mode.

Duplicate reporting disappeared when the app was build for production, which would be in line with [the official documentation](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects):

> This only applies to development mode. Lifecycles will not be double-invoked in production mode.

**Comment by joshuap** [comment]
@miktirr oh, that's a really good theory. I'll see if I can verify that locally. Thanks! 🙏

**Comment by joshuap** [comment]
Confirmed 💯 👍
