### ISSUE TITLE
Integrating our projects?

### ISSUE THREAD

**Issue by wuz** [honeybadger-io/honeybadger-react#34]
Hi there! I run the [unofficial React integration](https://github.com/lessonly/honeybadger-react) for Honeybadger. I am super excited to see this as an official project! I'd love to discuss deprecating my project and integrating it into this one. Let me know if there is a good process for doing that that you would like to follow!

**Comment by joshuap** [comment]
Hi @wuz, I don't remember seeing your project before--if I had I would have reached out to you when creating an official one. Thanks for your work on this!

Regarding process, I think it might help if you could take a look through our library and note if there are any differences between our implementation and yours. If you have made improvements that would benefit us, you could suggest changes to our library to port over--feel free to create issues for any changes you think would make sense, and we can discuss them there before implementing.

Once you're satisfied that you can move to using the official integration, you could update your README (and maybe do a final NPM release so that NPM gets the README as well) with a notice explaining the deprecation.

Does that work for you? Thanks again!

**Comment by wuz** [comment]
Hey @joshuap! That sounds like a plan! I'll work on deprecating my project this evening. I don't think there is much of a difference between our implementations, but I'll take a look and see if there is anything I can think of! 

I'm excited to help out!

**Comment by wuz** [comment]
Took me a lot longer then it should have, but it's been deprecated! 

https://www.npmjs.com/package/honeybadger-react

**Comment by joshuap** [comment]
Awesome, thanks @wuz!
